// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Talos.Shared.Data;

#nullable disable

namespace Talos.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201000546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Talos.Shared.Models.Compatibility", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("SourcePackageVersionid")
                        .HasColumnType("int");

                    b.Property<int>("TargetPackageid")
                        .HasColumnType("int");

                    b.Property<int>("compatibility_score")
                        .HasColumnType("int");

                    b.Property<int>("compatibility_type")
                        .HasColumnType("int");

                    b.Property<int>("confidence_level")
                        .HasColumnType("int");

                    b.Property<int>("detected_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("detection_date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("source_package_version_id")
                        .HasColumnType("int");

                    b.Property<int>("target_package_id")
                        .HasColumnType("int");

                    b.Property<string>("target_version_constraint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("SourcePackageVersionid");

                    b.HasIndex("TargetPackageid");

                    b.ToTable("compatibilities");
                });

            modelBuilder.Entity("Talos.Shared.Models.Follow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("followed_user_id")
                        .HasColumnType("int");

                    b.Property<int>("following_user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("followed_user_id");

                    b.HasIndex("following_user_id");

                    b.ToTable("follows");
                });

            modelBuilder.Entity("Talos.Shared.Models.Package", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("PackageManagerid")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("last_scraped_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("official_documentation_url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("package_manager_id")
                        .HasColumnType("int");

                    b.Property<string>("repository_url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("short_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("PackageManagerid");

                    b.ToTable("packages");
                });

            modelBuilder.Entity("Talos.Shared.Models.PackageManager", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("package_managers");
                });

            modelBuilder.Entity("Talos.Shared.Models.PackageVersion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Packageid")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("deprecation_message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("download_url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_deprecated")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("package_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("release_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("release_notes_url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Packageid");

                    b.ToTable("package_versions");
                });

            modelBuilder.Entity("Talos.Shared.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("Talos.Shared.Models.Template", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_public")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("license_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("template_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.HasIndex("user_id");

                    b.ToTable("templates");
                });

            modelBuilder.Entity("Talos.Shared.Models.TemplateDependencies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Templateid")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("package_id")
                        .HasColumnType("int");

                    b.Property<int>("template_id")
                        .HasColumnType("int");

                    b.Property<string>("version_constraint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Templateid");

                    b.HasIndex("package_id");

                    b.HasIndex("template_id");

                    b.ToTable("template_dependencies");
                });

            modelBuilder.Entity("Talos.Shared.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("private_template_limit")
                        .HasColumnType("int");

                    b.Property<string>("tier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Talos.Shared.Models.Compatibility", b =>
                {
                    b.HasOne("Talos.Shared.Models.PackageVersion", "SourcePackageVersion")
                        .WithMany("compatibilities_source")
                        .HasForeignKey("SourcePackageVersionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talos.Shared.Models.Package", "TargetPackage")
                        .WithMany("compatibilities_target")
                        .HasForeignKey("TargetPackageid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePackageVersion");

                    b.Navigation("TargetPackage");
                });

            modelBuilder.Entity("Talos.Shared.Models.Follow", b =>
                {
                    b.HasOne("Talos.Shared.Models.User", "FollowedUser")
                        .WithMany()
                        .HasForeignKey("followed_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talos.Shared.Models.User", "FollowingUser")
                        .WithMany()
                        .HasForeignKey("following_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedUser");

                    b.Navigation("FollowingUser");
                });

            modelBuilder.Entity("Talos.Shared.Models.Package", b =>
                {
                    b.HasOne("Talos.Shared.Models.PackageManager", "PackageManager")
                        .WithMany("packages")
                        .HasForeignKey("PackageManagerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageManager");
                });

            modelBuilder.Entity("Talos.Shared.Models.PackageVersion", b =>
                {
                    b.HasOne("Talos.Shared.Models.Package", "Package")
                        .WithMany("versions")
                        .HasForeignKey("Packageid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Talos.Shared.Models.Post", b =>
                {
                    b.HasOne("Talos.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Talos.Shared.Models.Template", b =>
                {
                    b.HasOne("Talos.Shared.Models.User", null)
                        .WithMany("templates")
                        .HasForeignKey("Userid");

                    b.HasOne("Talos.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Talos.Shared.Models.TemplateDependencies", b =>
                {
                    b.HasOne("Talos.Shared.Models.Template", null)
                        .WithMany("dependencies")
                        .HasForeignKey("Templateid");

                    b.HasOne("Talos.Shared.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("package_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talos.Shared.Models.Template", "Template")
                        .WithMany()
                        .HasForeignKey("template_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Talos.Shared.Models.Package", b =>
                {
                    b.Navigation("compatibilities_target");

                    b.Navigation("versions");
                });

            modelBuilder.Entity("Talos.Shared.Models.PackageManager", b =>
                {
                    b.Navigation("packages");
                });

            modelBuilder.Entity("Talos.Shared.Models.PackageVersion", b =>
                {
                    b.Navigation("compatibilities_source");
                });

            modelBuilder.Entity("Talos.Shared.Models.Template", b =>
                {
                    b.Navigation("dependencies");
                });

            modelBuilder.Entity("Talos.Shared.Models.User", b =>
                {
                    b.Navigation("templates");
                });
#pragma warning restore 612, 618
        }
    }
}
